config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_employee!
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
Hello world

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employee Recognition Platform</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <h1><%= link_to 'Company', root_path %></h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <nav>
    <h4>Navigation</4>
      <ul>
        <% if !employee_signed_in? %>
          <li><%= link_to 'Sing in', new_employee_session_path %></li>
          <li><%= link_to 'Sing up', new_employee_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sing out', destroy_employee_session_path, method: :delete %></li>
        <% end %>
      </ul>    
    <hr />
  </nav>
  <%= yield %>
  </body>
</html>